# Generated by Django 5.0.7 on 2024-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_questions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
