# Generated by Django 5.0.7 on 2024-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_enrollment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
